# Generated by Django 3.2.15 on 2022-08-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_userprof_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprof',
            options={'managed': True},
        ),
    ]
