# Generated by Django 3.2.15 on 2022-08-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_userprof_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='user_type',
            field=models.CharField(default='Client', max_length=20, null=True),
        ),
    ]
