# Generated by Django 3.2.15 on 2022-08-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20220829_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprof',
            name='user_type',
            field=models.CharField(blank=True, default='Client', max_length=20, null=True),
        ),
    ]
