# Generated by Django 3.2.15 on 2022-08-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_alter_userprof_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
