# Generated by Django 3.2.15 on 2022-08-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
