# Generated by Django 3.2.15 on 2022-08-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_userprof_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginOperational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('fileop', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='login',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprof',
            options={},
        ),
    ]
