# Generated by Django 3.2.15 on 2022-08-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_auto_20220829_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginoperational',
            name='fileop',
            field=models.FileField(upload_to='store'),
        ),
    ]
