# Generated by Django 3.2.15 on 2022-08-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_alter_loginoperational_fileop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginoperational',
            name='fileop',
            field=models.FileField(upload_to='media'),
        ),
    ]
