# Generated by Django 3.2.15 on 2022-08-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_alter_loginoperational_fileop'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('username_file_uploader', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
